# Generated by Django 5.0.7 on 2024-09-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_carusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='customer/')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='carusel',
            name='img',
            field=models.ImageField(upload_to='carusel/'),
        ),
    ]
